frase = input("Introduce una frase: ")

#upper(), lower(), title(), replace()) 
res = frase.upper()
print("Frase en mayusculas: ", res)
res = frase.lower()
print("Frase en minusculas: ", res)
res = frase.title()
print("Frase con cada palabra Capitaliza : ", res)
res = frase.replace("a", "o")
print("Frase remplazando las a por o: ", res)